ng g c source-code/basics/css/PseudoelementySourceComponent --module app -it -is 
ng g c source-code/basics/css/PseudoelementyBasnSourceComponent --module app -it -is 
ng g c source-code/basics/css/SelektorElementuSourceComponent --module app -it -is 
ng g c source-code/basics/css/SelektorAtrybutu2SourceComponent --module app -it -is 
ng g c source-code/basics/css/SelektorAtrybutu3SourceComponent --module app -it -is 
ng g c source-code/basics/css/SelektorAtrybutu1SourceComponent --module app -it -is 
ng g c source-code/basics/animations/WindowsXpSourceComponent --module app -it -is 
ng g c source-code/basics/animations/ZuluSourceComponent --module app -it -is 
ng g c source-code/basics/animations/LoadingSourceComponent --module app -it -is 
ng g c source-code/basics/html/MultimediaSourceComponent --module app -it -is
